repositories:
  - name: debian-trixie
    enabled: true
    uri: https://deb.debian.org/debian
    suite: trixie
    components: [main, contrib, non-free, non-free-firmware]
    architectures: [amd64]
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

  - name: debian-security
    enabled: true
    uri: https://security.debian.org/debian-security
    suite: trixie-security
    components: [main, contrib, non-free, non-free-firmware]
    architectures: [amd64]
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg

  - name: debian-updates
    enabled: true
    uri: https://deb.debian.org/debian
    suite: trixie-updates
    components: [main, contrib, non-free, non-free-firmware]
    architectures: [amd64]
    signed_by: /usr/share/keyrings/debian-archive-keyring.gpg
